version: 5.0.0-beta.{build}
branches:
  only:
  - master
skip_non_tags: true
clone_depth: 1
image: Visual Studio 2017
platform: Any CPU
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  ANGULAR_BUILD_TELEMETRY_OPTOUT: 1
  nodejs_version: "8"
  npm_auth_token:
    secure: 2G57TJwGR3m40UD1G7YdkowFzezrhOxEzMKwehKpb1vNPbsbFzfKRIFYVQ7WzZzE
install:
  - ps: Install-Product node $env:nodejs_version
  - set PATH=%APPDATA%\npm;%PATH%
  - ps: '"//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII'
  - npm whoami
  - npm install
build_script:
  - npm run build
  - dotnet build samples/ng-config-aspnetcore-sample/ng-config-aspnetcore-sample.csproj
test: off
deploy_script:
  - ps: |
      if ($env:deploy -eq "publish")
      {
        iex "npm publish ./dist/packages/ng-config --access=public"
        iex "npm publish ./dist/packages/ng-config-cache-http-loader --access=public"
        iex "npm publish ./dist/packages/ng-config-ngrx-store --access=public"
      }
cache:
  - node_modules -> package-lock.json
  - '%APPDATA%\npm-cache'
